#include "EventLog.h"
#include <strsafe.h>
#include "FilesystemMinifilterSvc.h"   // generated by mc.exe from FilesystemMinifilterSvc.mc (FS_EVENT)

HANDLE EventLogHandle;

BOOLEAN InitializeEventLog() {
	EventLogHandle = RegisterEventSourceW(0, L"FilesystemMinifilterMonitoringService");

	if (EventLogHandle == 0) {
		OutputDebugStringA("[Svc] RegisterEventSource FAILED\n");
		return FALSE;
	}
	return TRUE;
}

void DestroyEventLog() {
	if (EventLogHandle != 0) {
		DeregisterEventSource(EventLogHandle);
	}
}
PCSTR MajorFunctionName(ULONG MajorFunction)
{
    switch (MajorFunction)
    {
    case 0x00: return "CREATE";
    case 0x01: return "CREATE_NAMED_PIPE";
    case 0x02: return "CLOSE";
    case 0x03: return "READ";
    case 0x04: return "WRITE";
    case 0x05: return "QUERY_INFORMATION";
    case 0x06: return "SET_INFORMATION";
    case 0x07: return "QUERY_EA";
    case 0x08: return "SET_EA";
    case 0x09: return "FLUSH_BUFFERS";
    case 0x0A: return "QUERY_VOLUME_INFORMATION";
    case 0x0B: return "SET_VOLUME_INFORMATION";
    case 0x0C: return "DIRECTORY_CONTROL";
    case 0x0D: return "FILE_SYSTEM_CONTROL";
    case 0x0E: return "DEVICE_CONTROL";
    case 0x10: return "SHUTDOWN";
    case 0x12: return "CLEANUP";
    case 0x1B: return "PNP";
    default:   return "UNKNOWN";
    }
}

PCSTR FileInfoClassName(ULONG InfoClass)
{
    switch (InfoClass)
    {
    case  4: return "FileBasicInformation";
    case 10: return "FileRenameInformation";
    case 13: return "FileDispositionInformation";
    case 65: return "FileRenameInformationEx";
    case 64: return "FileDispositionInformationEx";
    default: return "Other";
    }
}
VOID LogFsTelemetry(_In_ PFS_TELEMETRY Log)
{
    CHAR  Base[512]{};
    CHAR  File[1100]{};
    CHAR  Enrichment[1200]{};
    PCSTR Strings[3] = { Base, File, Enrichment };

    StringCchPrintfA(
        Base, ARRAYSIZE(Base),
        "Op=%s (0x%02X.0x%02X)  PID=%llu  TID=%llu  "
        "Status=0x%08X  IrpFlags=0x%08X  Info=0x%IX",
        MajorFunctionName(Log->MajorFunction),
        Log->MajorFunction,
        Log->MinorFunction,
        (ULONG64)(ULONG_PTR)Log->ProcessId,
        (ULONG64)(ULONG_PTR)Log->ThreadId,
        Log->Status,
        Log->IrpFlags,
        Log->Information
    );

    StringCchPrintfA(
        File, ARRAYSIZE(File),
        "File=%ws "
        "DevObj=0x%IX  FileObj=0x%IX  Txn=0x%IX",
        Log->FileName,
        Log->DeviceObject,
        Log->FileObject,
        Log->Transaction
    );

    Enrichment[0] = '\0';

    switch (Log->MajorFunction)
    {
    case 0x00: // IRP_MJ_CREATE
    {
        if (Log->OpData.Enrichment.Create.IsRemoteOpen)
        {
            StringCchPrintfA(
                Enrichment, ARRAYSIZE(Enrichment),
                "REMOTE  Share=%ws  Client=%ws:%u  ECPs=%u",
                Log->OpData.Enrichment.Create.ShareName,
                Log->OpData.Enrichment.Create.RemoteAddress,
                Log->OpData.Enrichment.Create.RemotePort,
                Log->OpData.Enrichment.Create.EcpCount
            );
        }
        else if (Log->OpData.Enrichment.Create.EcpCount > 0)
        {
            StringCchPrintfA(
                Enrichment, ARRAYSIZE(Enrichment),
                "LOCAL  ECPs=%u",
                Log->OpData.Enrichment.Create.EcpCount
            );
        }
        break;
    }

    case 0x06: // IRP_MJ_SET_INFORMATION
    {
        ULONG InfoClass = Log->OpData.Enrichment.SetInformation.InfoClass;

        switch (InfoClass)
        {
        case 10: // FileRenameInformation
        case 65: // FileRenameInformationEx
            StringCchPrintfA(
                Enrichment, ARRAYSIZE(Enrichment),
                "%s  Target=%ws  ReplaceIfExists=%s",
                FileInfoClassName(InfoClass),
                Log->OpData.Enrichment.SetInformation.Rename.TargetFileName,
                Log->OpData.Enrichment.SetInformation.Rename.ReplaceIfExists ? "TRUE" : "FALSE"
            );
            break;

        case 13: // FileDispositionInformation
        case 64: // FileDispositionInformationEx
            StringCchPrintfA(
                Enrichment, ARRAYSIZE(Enrichment),
                "%s  DeleteFile=%s",
                FileInfoClassName(InfoClass),
                Log->OpData.Enrichment.SetInformation.Disposition.DeleteFile ? "TRUE" : "FALSE"
            );
            break;

        case 4: // FileBasicInformation
            StringCchPrintfA(
                Enrichment, ARRAYSIZE(Enrichment),
                "%s  CreationTime=0x%llX  LastWriteTime=0x%llX  Attrs=0x%08X",
                FileInfoClassName(InfoClass),
                Log->OpData.Enrichment.SetInformation.Basic.CreationTime.QuadPart,
                Log->OpData.Enrichment.SetInformation.Basic.LastWriteTime.QuadPart,
                Log->OpData.Enrichment.SetInformation.Basic.FileAttributes
            );
            break;

        default:
            StringCchPrintfA(
                Enrichment, ARRAYSIZE(Enrichment),
                "InfoClass=%u (%s)",
                InfoClass,
                FileInfoClassName(InfoClass)
            );
            break;
        }
        break;
    }

    default:
        break;
    }


    ReportEventA(EventLogHandle, 0, 1, FS_EVENT, 0, 3, 0, Strings, 0);
    
}